apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  annotations:
    apps.open-cluster-management.io/deployables: ''
  name: budget-app-dev
  namespace: budget-app-dev
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - budget-app-dev
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/deployables: 'budget-app-dev/budget-app-dev-subscription-1-quayacm-deployment-budget-app-dev-application,budget-app-dev/budget-app-dev-subscription-1-quayacm-deployment-budget-app-deployment,budget-app-dev/budget-app-dev-subscription-1-quayacm-deployment-budget-app-route,budget-app-dev/budget-app-dev-subscription-1-quayacm-deployment-budget-app-service'
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: quayacm-deployment
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: budget-app-dev
    app.kubernetes.io/part-of: budget-app-dev
    apps.open-cluster-management.io/reconcile-rate: medium
  name: budget-app-dev-subscription-1
  namespace: budget-app-dev
spec:
  channel: ggithubcom-grraaa-do480-apps-ns/ggithubcom-grraaa-do480-apps
  placement:
    placementRef:
      kind: PlacementRule
      name: budget-app-dev-placement-1
  secondaryChannel: ''
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  annotations: {}
  labels:
    app: budget-app-dev
  name: budget-app-dev-placement-1
  namespace: budget-app-dev
spec:
  clusterSelector:
    matchLabels:
      local-cluster: 'true'
